# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
"""
Tensor:
It's mostly about creating tensors, with a lot of specific functions provided.
Also, it telss the basic operations and how to build a basic tensors

Cuda:
It mentions how to run a tensor with the specified device.
In the later part of the documentation, it introduces the precision and tell us how to change and what the precision is
"""

"\nTensor:\nIt's mostly about creating tensors, with a lot of specific functions provided.\nAlso, it telss the basic operations and how to build a basic tensors\n\nCuda:\nIt mentions how to run a tensor with the specified device.\nIn the later part of the documentation, it introduces the precision and tell us how to change and what the precision is\n"

### 2. Create a random tensor with shape `(7, 7)`.


In [5]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
tensor.shape

torch.Size([7, 7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [18]:
# Create another random tensor
tensor_to_mul = torch.rand(1,7)

# Perform matrix multiplication
answer = torch.matmul(tensor, tensor_to_mul.mT)
answer, answer.shape

(tensor([[2.0087],
         [1.7927],
         [1.7941],
         [1.3588],
         [1.7351],
         [2.0526],
         [1.5566]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [26]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1,7)

# Matrix multiply tensors
torch.matmul(tensor1, tensor2.mT)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [46]:
# Set random seed on the GPU
# torch.cuda.manual_seed is specifically for GPU, torch.maual_seed can cover all devices including GPU
if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)
    answer = torch.rand(7,1, device="cuda")
    print(answer)

tensor([[0.1272],
        [0.8167],
        [0.5440],
        [0.6601],
        [0.2721],
        [0.9737],
        [0.3903]], device='cuda:0')



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [48]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():

# Create two random tensors on GPU
    tensor1 = torch.rand(2,3)
    tensor2 = torch.rand(2,3)

    print("tensor1: ", tensor1, "\n", "tensor2: ", tensor2)

tensor1:  tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) 
 tensor2:  tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [55]:
# Perform matmul on tensor_A and tensor_B
answer = torch.matmul(tensor1, tensor2.mT)

### 8. Find the maximum and minimum values of the output of 7.

In [58]:
answer
# Find max
torch.max(answer)

# Find min
torch.min(answer)

tensor(0.3647)

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
