In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Introduction to Tensors**

Creating Tensors

In [ ]:
# scaler
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
Matrix = torch.tensor([[7, 8],
                       [9, 10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix[0]

tensor([7, 8])

In [ ]:
Matrix[1]

tensor([ 9, 10])

In [ ]:
Matrix.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3], [3, 6, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]


tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Practice

In [ ]:
practice = torch.tensor([[[[[[1, 2, 3], [2,3,4]]]]]])
practice


tensor([[[[[[1, 2, 3],
            [2, 3, 4]]]]]])

In [ ]:
practice.shape

torch.Size([1, 1, 1, 1, 2, 3])

In [ ]:
practice[0][0][0][0][1][2]

tensor(4)

In [ ]:
# another
x = torch.tensor(2)
x.item()

2

Random tensors

Important part of neural networks

Flow:

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

rand:

https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of size  (3, 4)
random_tensor = torch.rand(1, 3, 4)
random_tensor



tensor([[[0.8528, 0.9912, 0.3096, 0.4640],
         [0.3855, 0.3047, 0.6189, 0.8221],
         [0.4268, 0.8010, 0.1654, 0.5582]]])

In [ ]:
random_tensor.ndim

3

# Image representation will be:

1. color channel --> red, green, blue

2. height

3. width

In [ ]:
# create a random tensor with similar shape to an image tensor
random__image_size_tensor = torch.rand(size = (3, 224, 224)) # color channels, height, width
random__image_size_tensor.shape, random__image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

**Practice**



---




In [ ]:
# create a random tensor with shape being [1, 2, 3]
practice_tensor = torch.rand(1, 2, 3)
practice_tensor

tensor([[[0.3233, 0.3091, 0.3255],
         [0.0166, 0.6372, 0.7118]]])

In [ ]:
practice_tensor.shape

torch.Size([1, 2, 3])

In [ ]:
# create a image like tensor using size
practice_tensor = torch.rand(size = (1,2,3))
practice_tensor

tensor([[[0.9673, 0.3623, 0.7783],
         [0.3179, 0.4031, 0.0389]]])

In [ ]:
practice_tensor.shape

torch.Size([1, 2, 3])


**My conclusion of using size or not using size function is that there are no differences**





---



Zeros and Ones

In [ ]:
# create a tensor of all zeros
zero = torch.zeros(size = (3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

# Creating a range of tensors and tensors-like

In [ ]:
torch.arange(0, 11)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# They are the same
torch.arange(0, 10)
torch.arange(start=0, end=10, step=1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=torch.arange(1,10))
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

1. The default datatype is float32
2. we can specify dtype when creating a tensor
3. It will be one of the 3 big errors in Pytorch coding







---


補充 3 big issues：
1. Tensors not right datatype  --> check with `tensor.dtype`
2. Tensors not right shape  --> check with `tensor.shape`
3. Tensors not on the right device  --> check with `tensor.device`


In [ ]:
need_to_know = torch.tensor([3, 6, 9],
                            dtype=None, # datatype (eg. float32, float16)
                            device="cpu", # what device is your tensor on (eg. cpu, cuda)
                            requires_grad=False # whether or not to track gradients with this tensor's operation
                            )
need_to_know


tensor([3, 6, 9])

In [ ]:
float_tensor_32 = torch.tensor([3.0, 6.0, 9.0],
                            dtype=None)
float_tensor_32.dtype

torch.float32

In [ ]:
# These 3 are the same
float_tensor_16 = torch.tensor([3.0, 6.0, 9.0],
                                dtype = torch.float16)

float_tensor_16 = float_tensor_32.type(torch.float16)

float_tensor_16 = float_tensor_32.type(torch.half)

float_tensor_16

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_tensor_16 * float_tensor_32

tensor([ 9., 36., 81.])

# Practice

Create a tensor and provides information

In [ ]:
practice = torch.rand(3, 1000)

In [ ]:
print("The tensor will be: \n", practice)
print("\n", "Datatype: ", practice.dtype)
print("Shape: ", practice.dtype)
print("Device: ", practice.device)

The tensor will be: 
 tensor([[0.3248, 0.8694, 0.3367,  ..., 0.2347, 0.2820, 0.0747],
        [0.6033, 0.9095, 0.8280,  ..., 0.4043, 0.4108, 0.9129],
        [0.4301, 0.9272, 0.0629,  ..., 0.3615, 0.6832, 0.7246]])

 Datatype:  torch.float32
Shape:  torch.float32
Device:  cpu


In [ ]:
# change the dtype, shape, device
practice = practice.type(torch.float16)

# shape does not change like calling a function
# I reckon it requires manually change the tensor since we are the one to decide whcih info is to change or delete

# device hasn't been covered yet

# Manipulating Tensors (tensor operations)

Tensor operations include:
1. Addition
2. Subtraction
3. Mutiplication (element-wise)
4. Division
5. Matrix multiplication

In [ ]:
# The value of tensor won't change since we haven't assign the new value to it
tensor = torch.tensor([1,2,3])

In [ ]:
tensor + 100

tensor([101, 102, 103])

In [ ]:
tensor * 100

tensor([100, 200, 300])

In [ ]:
tensor - 100

tensor([-99, -98, -97])

#Mutiplication
1. element wise multiplication

2. matrix multiplication
  
  For matrix multiplication
  
  1. the **inner dmensions** must match:
  * `(3,2) @ (3,2)` won't work
  * `(3,2) @ (2,3)` will work
  * `(2,3) @ (2,3)` will work
  * `(2,3) @ (2,3)` won't work

2. The resulting matrix has the shape of the outer dimensions
* `(2,3) @ (3,2) -> (2,2)`
* `(3,2) @ (2,3) -> (3,3)`



**commands**
1. torch.matmul()
2. torch.mm()
3. tensor_A @ tensor_B

In [ ]:
torch.rand(3,10)

tensor([[0.3064, 0.1697, 0.2678, 0.0799, 0.8020, 0.3930, 0.7081, 0.7640, 0.5415,
         0.6362],
        [0.0845, 0.6636, 0.0315, 0.9552, 0.7677, 0.7087, 0.7006, 0.9976, 0.6552,
         0.1700],
        [0.6738, 0.7953, 0.1984, 0.6419, 0.9467, 0.9158, 0.5398, 0.6818, 0.8625,
         0.5106]])

In [ ]:
# Element wise multiplication
tensor = torch.tensor([1,2,3])
print(tensor, "*", tensor, "\n =")
tensor*tensor

tensor([1, 2, 3]) * tensor([1, 2, 3]) 
 =


tensor([1, 4, 9])

In [ ]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

The runtime of matmul is faster than using for loop to calculate value

In [ ]:
%%time
value = 0

for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 1.66 ms, sys: 102 µs, total: 1.76 ms
Wall time: 3.43 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 348 µs, sys: 0 ns, total: 348 µs
Wall time: 483 µs


tensor(14)

To fix the shape issue, we often **transpose** the matrix

In [ ]:
temp = torch.rand(3,2)
temp

tensor([[0.0883, 0.6529],
        [0.1651, 0.4241],
        [0.3824, 0.5072]])

In [ ]:
# transposed
temp.T

tensor([[0.0883, 0.1651, 0.3824],
        [0.6529, 0.4241, 0.5072]])

In [ ]:
# shape doesn't match
temp_A = torch.rand(3,2)
temp_B = torch.rand(3,2)
torch.mm(temp_A, temp_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# shape problem fixed (transpose B)
torch.mm(temp_A, temp_B.T)


tensor([[1.1715, 0.7952, 0.3029],
        [0.5284, 0.3613, 0.0959],
        [0.9024, 0.6162, 0.1745]])

Finding the min, max, mean, sum (tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# mean --> note: torch.mean() requirees a tensor of float32 datatype to work
x.dtype

torch.int64

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# sum
torch.sum(x), x.sum()

Finding the positional min and max

In [ ]:
x

In [ ]:
# Find the position of the muinimum number
x.argmin()

In [ ]:
x[0]

In [ ]:
# Find the position in tensor that has the max value with argmax()

In [ ]:
x.argmax()

In [ ]:
x[9]

Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of input with dimensions permuted (swapped) in a certain way

In [ ]:
# Lets's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z will also change x (Cuz a view of a tensor shares the same memory as the original input)

In [ ]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze
practice = torch.rand(3,3,1,1,1,2,1,3)
practice.shape

torch.Size([3, 3, 1, 1, 1, 2, 1, 3])

In [ ]:
print(f"Previous tensor shape: {practice.shape}", "\n")
print(f"Only remove the dimension 3: {practice.squeeze(dim=3).shape}", "\n")
print(f"Try to remove the dimention which is not 1: {practice.squeeze(dim=1).shape}", "\n")
print(f"New tensor shape: {practice.squeeze().shape}", "\n")

Previous tensor shape: torch.Size([3, 3, 1, 1, 1, 2, 1, 3]) 

Only remove the dimension 3: torch.Size([3, 3, 1, 1, 2, 1, 3]) 

Try to remove the dimention which is not 1: torch.Size([3, 3, 1, 1, 1, 2, 1, 3]) 

New tensor shape: torch.Size([3, 3, 2, 3]) 



In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous tensor shape: {practice.shape}", "\n")
print(f"Insert a new dim at dim 0: {practice.unsqueeze(dim=0).shape}")

Previous tensor shape: torch.Size([3, 3, 1, 1, 1, 2, 1, 3]) 

Insert a new dim at dim 0: torch.Size([1, 3, 3, 1, 1, 1, 2, 1, 3])


In [ ]:
# torch.permute (This is a view) - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # (height, width, color_channels)

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}", "\n")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3]) 

New shape: torch.Size([3, 224, 224])


Indexing (selecting data from tensors)

Similar with numpy

In [ ]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0], x[0][2][2]

(tensor(1), tensor(9))

In [ ]:
# Using ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors & Numpy

Numpy is a popular scientific Python numerical computing library

ANd because of this, PytTorch has functionality to interact with it
* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`


Notice:

When using torch.from_numpy(), PyTorch will inherit numpy's default dtype which is `float64` wheras PyTorch's regular tensor's default dtype is `float32`.

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will this do to `tensor` ?
array =  array + 1
array, tensor


(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = torch.Tensor.numpy(tensor)
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random number to try and make them better representations of the data -> again -> again -> again......`

To reduce the randomness in neural networds and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness

https://docs.pytorch.org/docs/stable/notes/randomness.html

In [ ]:
import torch

# create 2 random torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4592, 0.8290, 0.7593, 0.7156],
        [0.1529, 0.6824, 0.0683, 0.9913],
        [0.6465, 0.3274, 0.8446, 0.0169]])
tensor([[0.6925, 0.5336, 0.8485, 0.7372],
        [0.6323, 0.5558, 0.4576, 0.1193],
        [0.1913, 0.3775, 0.6969, 0.9600]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good)

## Getting GPU
* Use google collab's for free GPU
* Use your own GPU
* Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them.

For point 2, 3 PyTorch + GPU drivers(CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation.
https://pytorch.org/get-started/locally/

In [ ]:
!nvidia-smi

Tue Nov 25 22:51:29 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   64C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. check for GPU access with PyTorch

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
# Count number if devices
torch.cuda.device_count()

1


## Putting tensors(and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], device="cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU


In [ ]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Excercise & Extra curriculum
https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises
